"""Add is_archived to Event

Revision ID: 7621c7fc8acd
Revises: 8c27696cbb5f
Create Date: 2025-04-16 11:11:03.159710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7621c7fc8acd'
down_revision = '8c27696cbb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
