"""Initial migration

Revision ID: a9acf04d729f
Revises: e4d313c16811
Create Date: 2025-04-02 11:23:40.327115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9acf04d729f'
down_revision = 'e4d313c16811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('best_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('best_round', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_round', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('selected_round')

    with op.batch_alter_table('fight', schema=None) as batch_op:
        batch_op.drop_column('best_round')
        batch_op.drop_column('best_method')
        batch_op.drop_column('round')

    # ### end Alembic commands ###
