"""Initial migration

Revision ID: e4d313c16811
Revises: 
Create Date: 2025-04-01 10:12:23.028566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d313c16811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter1', sa.String(length=100), nullable=False),
    sa.Column('fighter2', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('favorite', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('selected_fighter', sa.String(length=100), nullable=False),
    sa.Column('selected_method', sa.String(length=100), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick')
    op.drop_table('fight')
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###
